target_path: ~/Desktop/test_output
engine: blender
scene_config:
  scene_path: core/interfaces/blender/tyless-5-objects.blend
  scene_name: Scene
  camera_names:
    - Camera
  axis_names:
    - Axis
  element_names:
    - obj_01
    - obj_02
    - obj_03
    - obj_04
    - obj_05
  light_names:
    - Light
sweep_config:
    step: 10
    yaw_limits: [0.0, 90.0]
    roll_limits: [-180.0, 180.0]
    camera_height_limits: [1.0, 10.0]
    random_seed: 0