# General settings
engine: blender
target_path: test_output

# Camera settings
random_seed: 0
resolution: [256, 256]
samples: 128

# Scene settings
scene_config:
  scene_path: core/interfaces/blender/scenes/tyless-5-objects.blend
  scene_name: Scene
  camera_names:
    - Camera
  axis_names:
    - Axis
  element_names:
    - obj_01
    - obj_02
    - obj_03
    - obj_04
    - obj_05
  light_names:
    - Light

# Sweep settings
sweep_config:
    name: example_sweep
    step: 10
    yaw_limits: [0.0, 0.0]
    roll_limits: [0.0, 0.0]
    camera_height_limits: [1.0, 1.0]
    light_energy_limits: [1000.0, 1000.0]
    
